[package]
name = "wasm-test"
version = "0.1.0"
authors = ["MinusGix <minusgix@gmail.com>"]
edition = "2018"
description = "Wasm testing"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
